import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";

export default {
  input: "bin/email.js",
  output: {
    file: "package/lib/email.mjs",
    format: "es",
    inlineDynamicImports: true,
  },
  plugins: [nodeResolve({ preferBuiltins: true }), commonjs(), json()],
  external: [
    "fs",
    "path",
    "stream",
    "util",
    "events",
    "buffer",
    "string_decoder",
    "crypto",
    "os",
    "tty",
    "process",
    "net",
    "tls",
    "dns",
    "http",
    "https",
    "zlib",
    "url",
    "querystring",
    "child_process",
    "assert",
    "punycode",
    "node:fs",
    "node:path",
    "node:stream",
    "node:util",
    "node:events",
    "node:buffer",
    "node:string_decoder",
    "node:crypto",
    "node:os",
    "node:tty",
    "node:process",
    "node:net",
    "node:tls",
    "node:dns",
    "node:http",
    "node:https",
    "node:zlib",
    "node:url",
    "node:querystring",
    "node:child_process",
    "node:assert",
    "node:punycode",
  ],
};
